// Investment Information Constants
// Contains detailed information about each investment instrument

export const investmentInfo = {
  ppf: {
    name: 'Public Provident Fund (PPF)',
    description: 'A long-term savings scheme backed by the Government of India with tax benefits.',
    features: [
      'Tax-exempt interest and maturity (EEE - Exempt, Exempt, Taxed on withdrawal)',
      'Sovereign guarantee',
      '15-year lock-in period',
      'Can be extended in blocks of 5 years',
      'Partial withdrawals allowed from 7th year',
      'Loan facility available from 3rd to 6th year',
    ],
    taxBenefits: [
      'Deduction under Section 80C up to ₹1.5 lakh',
      'Interest earned is tax-free',
      'Maturity amount is tax-free',
    ],
    eligibility: [
      'Indian residents only',
      'Individuals and HUFs',
      'One account per person (can have account for minor)',
    ],
    lockInPeriod: '15 years',
    minInvestment: '₹500 per year',
    maxInvestment: '₹1.5 lakh per year',
  },
  fd: {
    name: 'Fixed Deposit (FD)',
    description: 'A time deposit offered by banks with fixed interest rate over a specified period.',
    features: [
      'Assured, fixed returns',
      'Covered by DICGC up to ₹5 lakh',
      'Flexible tenure options',
      'Premature withdrawal allowed with penalty',
    ],
    taxBenefits: [
      'Interest taxable as per income tax slab',
      'TDS applicable if interest exceeds ₹40,000 (₹50,000 for senior citizens)',
    ],
    eligibility: [
      'Any individual',
      'Minors through guardian',
      'Joint accounts allowed',
    ],
    lockInPeriod: 'Depends on chosen tenure',
    minInvestment: 'Varies by bank (typically ₹1,000)',
    maxInvestment: 'No limit',
  },
  sip: {
    name: 'Systematic Investment Plan (SIP)',
    description: 'Regular investments in mutual funds to average out market volatility.',
    features: [
      'Rupee-cost averaging',
      'Disciplined investing',
      'Flexible investment amounts',
      'Can start with as low as ₹500',
      'Step-up SIP options available',
    ],
    taxBenefits: [
      'Equity funds: Long-term capital gains tax after 1 year (10% above ₹1 lakh)',
      'Debt funds: Long-term capital gains tax after 3 years',
      'ELSS SIPs qualify for Section 80C deduction',
    ],
    eligibility: [
      'Any individual',
      'Minors through guardian',
      'NRIs allowed',
    ],
    lockInPeriod: 'No lock-in (except ELSS - 3 years)',
    minInvestment: '₹500 per month',
    maxInvestment: 'No limit',
  },
  ssy: {
    name: 'Sukanya Samriddhi Yojana (SSY)',
    description: 'A savings scheme exclusively for the girl child with attractive interest rates.',
    features: [
      'Exclusively for girl child',
      'High fixed interest rate',
      'EEE tax status (Exempt, Exempt, Exempt)',
      'Account matures when girl child turns 21',
      'Partial withdrawal allowed after 18 years for education/marriage',
    ],
    taxBenefits: [
      'Deduction under Section 80C up to ₹1.5 lakh',
      'Interest earned is tax-free',
      'Maturity amount is tax-free',
    ],
    eligibility: [
      'Girl child below 10 years',
      'Parents or legal guardians can open',
      'Maximum 2 accounts per parent (one per girl child)',
    ],
    lockInPeriod: 'Till girl child turns 21 years',
    minInvestment: '₹250 per year',
    maxInvestment: '₹1.5 lakh per year',
  },
  nsc: {
    name: 'National Savings Certificate (NSC)',
    description: 'A fixed income investment scheme with guaranteed returns.',
    features: [
      'Fixed interest rate',
      'Compounded annually',
      'Interest paid at maturity',
      'Available at post offices',
    ],
    taxBenefits: [
      'Deduction under Section 80C',
      'Interest earned is taxable',
      'Interest reinvested qualifies for deduction',
    ],
    eligibility: [
      'Any individual',
      'Minors through guardian',
      'HUFs allowed',
    ],
    lockInPeriod: '5 years',
    minInvestment: '₹1,000',
    maxInvestment: 'No limit',
  },
  scss: {
    name: 'Senior Citizens Savings Scheme (SCSS)',
    description: 'A savings scheme exclusively for senior citizens with high interest rates.',
    features: [
      'Exclusively for senior citizens (60+ years)',
      'High interest rate',
      'Quarterly interest payments',
      'Can be extended for 3 more years',
    ],
    taxBenefits: [
      'Deduction under Section 80C up to ₹1.5 lakh',
      'Interest taxable as per income tax slab',
      'TDS applicable if interest exceeds ₹40,000',
    ],
    eligibility: [
      'Age 60 years or above',
      'Age 55+ years for retired defense personnel',
      'Individual or joint account with spouse',
    ],
    lockInPeriod: '5 years (extendable)',
    minInvestment: '₹1,000',
    maxInvestment: '₹30 lakh',
  },
  pomis: {
    name: 'Post Office Monthly Income Scheme (POMIS)',
    description: 'A savings scheme that provides fixed monthly income with sovereign guarantee.',
    features: [
      'Fixed monthly income',
      'Sovereign guarantee',
      'Fixed 5-year tenure',
      'Joint account option available',
      'Premature withdrawal allowed with penalty',
    ],
    taxBenefits: [
      'Interest taxable as per income tax slab',
      'TDS applicable if interest exceeds ₹40,000/year',
      'No tax deduction benefit (unlike PPF/NSC)',
    ],
    eligibility: [
      'Any individual',
      'Minors through guardian',
      'Joint accounts allowed',
      'No age restriction',
    ],
    lockInPeriod: '5 years',
    minInvestment: '₹1,000',
    maxInvestment: '₹9 lakh (single account), ₹15 lakh (joint account)',
  },
  sgb: {
    name: 'Sovereign Gold Bonds (SGB)',
    description: 'Government securities denominated in grams of gold with fixed interest.',
    features: [
      'Denominated in grams of gold',
      'Fixed interest rate of 2.5% p.a.',
      'Interest paid semi-annually',
      'Capital appreciation linked to gold prices',
      'Exit option after 5 years',
    ],
    taxBenefits: [
      'Capital gains on redemption are tax-exempt',
      'Interest taxable as per income tax slab',
      'TDS applicable on interest',
    ],
    eligibility: [
      'Any individual',
      'HUFs, trusts, charitable institutions',
      'NRIs not allowed',
    ],
    lockInPeriod: '8 years (exit option after 5 years)',
    minInvestment: '1 gram of gold',
    maxInvestment: '4 kg per person per financial year',
  },
  nps: {
    name: 'National Pension System (NPS)',
    description: 'A voluntary retirement savings scheme with tax benefits.',
    features: [
      'Long-term retirement planning',
      'Tax benefits under Section 80C and 80CCD(1B)',
      'Auto choice or active choice of asset allocation',
      'Market-linked returns',
    ],
    taxBenefits: [
      'Deduction under Section 80C up to ₹1.5 lakh',
      'Additional deduction under Section 80CCD(1B) up to ₹50,000',
      '60% withdrawal tax-free at maturity',
      '40% withdrawal taxable',
    ],
    eligibility: [
      'Any Indian citizen between 18-70 years',
      'NRIs allowed',
    ],
    lockInPeriod: 'Till age 60 years',
    minInvestment: '₹500 per contribution',
    maxInvestment: 'No limit',
  },
  elss: {
    name: 'Equity-Linked Savings Scheme (ELSS)',
    description: 'Tax-saving mutual funds with equity exposure and 3-year lock-in.',
    features: [
      'Tax deduction under Section 80C',
      'Equity exposure for potential high returns',
      'Minimum 3-year lock-in period',
      'Can invest via SIP or lumpsum',
    ],
    taxBenefits: [
      'Deduction under Section 80C up to ₹1.5 lakh',
      'Long-term capital gains tax after 1 year (10% above ₹1 lakh)',
    ],
    eligibility: [
      'Any individual',
      'HUFs allowed',
    ],
    lockInPeriod: '3 years',
    minInvestment: '₹500',
    maxInvestment: 'No limit',
  },
  equity: {
    name: 'Direct Equity (Stocks)',
    description: 'Direct investment in company shares listed on stock exchanges.',
    features: [
      'Direct ownership in companies',
      'Potential for high returns',
      'High risk',
      'Dividend income',
      'Capital appreciation',
    ],
    taxBenefits: [
      'Long-term capital gains tax after 1 year (10% above ₹1 lakh)',
      'Short-term capital gains tax at 15%',
      'Dividend income taxable',
    ],
    eligibility: [
      'Any individual',
      'Minors through guardian',
      'Need Demat account',
    ],
    lockInPeriod: 'No lock-in',
    minInvestment: '1 share',
    maxInvestment: 'No limit',
  },
  rd: {
    name: 'Recurring Deposit (RD)',
    description: 'A monthly recurring deposit scheme offered by banks with fixed interest rate.',
    features: [
      'Fixed monthly contributions',
      'Flexible tenure options',
      'Premature withdrawal penalty',
      'Loan facility available',
      'Covered by DICGC up to ₹5 lakh',
    ],
    taxBenefits: [
      'Interest taxable as per income tax slab',
      'TDS applicable if interest exceeds ₹40,000/year (₹50,000 for senior citizens)',
      'Form 15G/15H for TDS exemption',
    ],
    eligibility: [
      'Any individual',
      'Minors through guardian',
      'Joint accounts allowed',
    ],
    lockInPeriod: 'Depends on chosen tenure',
    minInvestment: '₹500 per month',
    maxInvestment: 'No limit',
  },
  etf: {
    name: 'Exchange Traded Funds (ETFs)',
    description: 'Market-linked investment funds that track indices and trade on stock exchanges like stocks, with lower expense ratios than mutual funds.',
    features: [
      'Lower expense ratios (0.05-0.50%) vs Mutual Funds (1-2%)',
      'Index tracking',
      'Real-time trading on stock exchanges',
      'Tax efficiency',
      'Diversification benefits',
      'High liquidity',
    ],
    taxBenefits: [
      'Equity ETFs: LTCG (10% above ₹1L exemption) after 1 year, STCG (15%) before 1 year',
      'Debt ETFs: LTCG (20% with indexation) after 3 years',
      'Gold ETFs: LTCG (20% with indexation) after 3 years',
      'International ETFs: LTCG (10% above ₹1L exemption) after 1 year',
    ],
    eligibility: [
      'Any individual',
      'Minors through guardian',
      'Need Demat account',
      'NRIs allowed',
    ],
    lockInPeriod: 'No lock-in',
    minInvestment: '1 unit (typically ₹500+)',
    maxInvestment: 'No limit',
  },
  debtMutualFund: {
    name: 'Debt Mutual Funds',
    description: 'Mutual funds that invest in fixed-income securities like government bonds, corporate bonds, and money market instruments, offering lower risk than equity funds with steady returns.',
    features: [
      'Tax efficiency (indexation benefit for LTCG after 3 years)',
      'Lower risk than equity funds',
      'Higher returns than FDs (post-tax)',
      'Liquidity options available',
      'No TDS on redemption',
      'Can invest via SIP or lumpsum',
    ],
    taxBenefits: [
      'Long-term capital gains (held >3 years): 20% with indexation benefit - More tax-efficient than FDs',
      'Short-term capital gains (held <3 years): Taxed as per income tax slab',
      'No TDS on redemption (unlike FDs)',
      'Indexation benefit reduces effective tax rate significantly',
    ],
    eligibility: [
      'Any individual',
      'Minors through guardian',
      'HUFs allowed',
      'NRIs allowed',
    ],
    lockInPeriod: 'No lock-in (for tax efficiency, hold >3 years)',
    minInvestment: '₹500 per month (SIP) or ₹1,000 (Lumpsum)',
    maxInvestment: 'No limit',
  },
  reits: {
    name: 'Real Estate Investment Trusts (REITs)',
    description: 'Listed investment vehicles that own and operate income-generating real estate properties, providing regular dividend income and potential capital appreciation.',
    features: [
      'Regular dividend income (typically 6-8% yield)',
      'Real estate exposure without direct property ownership',
      'Listed on stock exchanges (liquidity)',
      'Lower minimum investment than physical real estate',
      'Professional management',
      'Diversification across multiple properties',
    ],
    taxBenefits: [
      'Dividend income: Taxable as per income tax slab',
      'Long-term capital gains (held >1 year): 10% above ₹1 lakh exemption',
      'Short-term capital gains (held <1 year): 15% tax',
      'No indexation benefit on capital gains',
    ],
    eligibility: [
      'Any individual',
      'Minors through guardian',
      'Need Demat account',
      'NRIs allowed',
    ],
    lockInPeriod: 'No lock-in',
    minInvestment: '₹1,000',
    maxInvestment: 'No limit',
    risks: [
      'Market risk: REIT prices fluctuate based on market conditions and real estate performance',
      'Interest rate risk: REITs may be sensitive to interest rate changes',
      'Property-specific risk: Performance depends on underlying real estate properties',
      'Liquidity risk: Though listed, trading volumes may be lower than large-cap stocks',
    ],
  },
  bonds54EC: {
    name: '54EC Bonds (Capital Gain Bonds)',
    description: 'Tax-saving bonds that exempt long-term capital gains tax from property sale. Must invest within 6 months of property sale to avail tax exemption.',
    features: [
      'Exempts long-term capital gains tax (up to ₹50L per financial year)',
      'Fixed 5-year lock-in period',
      'Issued by NHAI, REC, PFC',
      'Sovereign guarantee (government-backed)',
      'Interest paid annually or at maturity',
      'No premature withdrawal allowed',
    ],
    taxBenefits: [
      'Exempts long-term capital gains tax on property sale (up to ₹50L per FY)',
      'Interest taxable as per income tax slab',
      'TDS applicable on interest',
      'Must invest within 6 months of property sale date',
    ],
    eligibility: [
      'Any individual who has sold property',
      'Investment must be made within 6 months of property sale',
      'HUFs allowed',
      'NRIs allowed',
    ],
    lockInPeriod: '5 years (fixed)',
    minInvestment: '₹1,000',
    maxInvestment: '₹50 lakh per financial year (or capital gain amount, whichever is lower)',
  },
}

export default investmentInfo