// Generated from: features\calculators\debt-mutual-fund.feature
import { test } from "playwright-bdd";

test.describe('Debt Mutual Fund Calculator', () => {

  test.beforeEach('Background', async ({ Given, And, page }, testInfo) => { if (testInfo.error) return;
    await Given('the default tax slab is 30 percent', null, { page }); 
    await And('inflation adjustment is off', null, { page }); 
    await Given('I am on the debt mutual fund calculator page', null, { page }); 
  });
  
  test('DMF-01 Calculator loads with documented default values', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund'] }, async ({ Then, And, page }) => { 
    await Then('the debt MF investment type should be "sip"', null, { page }); 
    await And('the debt MF amount should be 5000', null, { page }); 
    await And('the debt MF tenure should be 5 years', null, { page }); 
    await And('the debt MF expected return should match the short-term fund default rate', null, { page }); 
  });

  test('DMF-02 Results update in real time without Calculate button', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund'] }, async ({ When, Then, page }) => { 
    await When('I change the debt MF amount to 10000', null, { page }); 
    await Then('the debt MF corpus value should update without clicking calculate', null, { page }); 
  });

  test('DMF-03 Results panel shows Money in Hand post-tax', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund'] }, async ({ Then, And, page }) => { 
    await Then('I should see the debt MF money in hand amount', null, { page }); 
    await And('the debt MF post-tax amount should be less than or equal to the corpus value', null, { page }); 
  });

  test('DMF-04 Tax breakdown visible with indexation rule explanation', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund'] }, async ({ Then, And, page }) => { 
    await Then('I should see the debt MF tax breakdown section', null, { page }); 
    await And('the debt MF tax rule should mention indexation benefit', null, { page }); 
  });

  test('DMF-05 Inflation toggle affects spending power when ON', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund'] }, async ({ Given, When, Then, page }) => { 
    await Given('inflation adjustment is on', null, { page }); 
    await When('I view the debt MF results panel', null, { page }); 
    await Then('I should see debt MF actual spending power adjusted for inflation', null, { page }); 
  });

  test('DMF-06 Evolution table shows year-wise breakdown', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund'] }, async ({ Then, And, page }) => { 
    await Then('I should see the debt MF evolution table', null, { page }); 
    await And('the debt MF evolution table should have at least 1 year row', null, { page }); 
  });

  test('DMF-07 Info panel shows expected return rates by fund type', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund'] }, async ({ Then, And, page }) => { 
    await Then('I should see the debt MF info panel', null, { page }); 
    await And('the debt MF info panel should show short-term debt return rate', null, { page }); 
  });

  test('DMF-08 Invalid min amount shows inline validation error', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund', '@edge'] }, async ({ When, Then, page }) => { 
    await When('I enter debt MF amount 499', null, { page }); 
    await Then('I should see debt MF validation error "Minimum investment amount is ₹500"', null, { page }); 
  });

  test('DMF-09 Invalid max tenure shows inline validation error', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund', '@edge'] }, async ({ When, Then, page }) => { 
    await When('I enter debt MF tenure 51 years', null, { page }); 
    await Then('I should see debt MF validation error "Maximum tenure is 50 years"', null, { page }); 
  });

  test('DMF-10 Zero or empty input does not crash', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund', '@edge'] }, async ({ When, Then, And, page }) => { 
    await When('I clear the debt MF amount', null, { page }); 
    await Then('the debt MF calculator should show empty results state', null, { page }); 
    await And('the debt MF page should not crash', null, { page }); 
  });

  test('DMF-11 Negative input rejected or clamped', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund', '@edge'] }, async ({ When, Then, page }) => { 
    await When('I enter debt MF amount -1000', null, { page }); 
    await Then('I should see a debt MF validation error or the value should be rejected', null, { page }); 
  });

  test('DMF-12 Non-numeric input rejected', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund', '@edge'] }, async ({ When, Then, page }) => { 
    await When('I enter debt MF amount "abc"', null, { page }); 
    await Then('I should see a debt MF validation error for amount', null, { page }); 
  });

  test('DMF-13 Extremely large value handled without overflow', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund', '@edge'] }, async ({ When, Then, And, page }) => { 
    await When('I enter debt MF amount 100000', null, { page }); 
    await And('I set debt MF tenure to 10 years', null, { page }); 
    await Then('the debt MF corpus value should be approximately 17904241 within tolerance 5000', null, { page }); 
  });

  test.describe('DMF-14 Golden calculation matches reference value', () => {

    test('Example #1', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund'] }, async ({ When, Then, And, page }) => { 
      await When('I set debt MF inputs from golden "DMF-14"', null, { page }); 
      await Then('the debt MF corpus value should match golden "DMF-14" field corpusValue', null, { page }); 
      await And('the debt MF post-tax amount should match golden "DMF-14" field postTaxAmount', null, { page }); 
    });

    test('Example #2', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund'] }, async ({ When, Then, And, page }) => { 
      await When('I set debt MF inputs from golden "DMF-20"', null, { page }); 
      await Then('the debt MF corpus value should match golden "DMF-20" field corpusValue', null, { page }); 
      await And('the debt MF post-tax amount should match golden "DMF-20" field postTaxAmount', null, { page }); 
    });

  });

  test('DMF-15 Pie chart renders or graceful fallback', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund', '@edge'] }, async ({ Then, page }) => { 
    await Then('I should see the debt MF investment breakdown chart or fallback', null, { page }); 
  });

  test('DMF-20 Indexation benefit reduces LTCG tax after 3 years', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund'] }, async ({ When, Then, And, page }) => { 
    await When('I set debt MF inputs from golden "DMF-20"', null, { page }); 
    await Then('the debt MF tax rate label should be "20% LTCG (Indexed)"', null, { page }); 
    await And('the debt MF tax amount should be approximately 5844 within tolerance 50', null, { page }); 
    await And('I should see debt MF indexation benefit details', null, { page }); 
  });

  test('DMF-21 STCG taxed at income slab when tenure under 3 years', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund'] }, async ({ When, Then, And, page }) => { 
    await When('I set debt MF inputs from golden "DMF-21-STCG"', null, { page }); 
    await Then('the debt MF tax rate label should be "30% slab"', null, { page }); 
    await And('the debt MF tax amount should be approximately 2952 within tolerance 50', null, { page }); 
  });

  test('DMF-21 LTCG indexation applies at exactly 3 years tenure boundary', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund'] }, async ({ When, Then, And, page }) => { 
    await When('I set debt MF inputs from golden "DMF-21-LTCG"', null, { page }); 
    await Then('the debt MF tax rate label should be "20% LTCG (Indexed)"', null, { page }); 
    await And('the debt MF post-tax amount should match golden "DMF-21-LTCG" field postTaxAmount', null, { page }); 
  });

  test('DMF-22 SIP mode vs lumpsum mode produce different corpus values', { tag: ['@smoke', '@regression', '@tax', '@calculator-debt-mutual-fund'] }, async ({ When, Then, And, page }) => { 
    await When('I set debt MF inputs from golden "DMF-22-SIP"', null, { page }); 
    await Then('the debt MF corpus value should match golden "DMF-22-SIP" field corpusValue', null, { page }); 
    await When('I select debt MF investment type "lumpsum"', null, { page }); 
    await And('I set debt MF inputs from golden "DMF-22-LUMPSUM"', null, { page }); 
    await Then('the debt MF corpus value should match golden "DMF-22-LUMPSUM" field corpusValue', null, { page }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features\\calculators\\debt-mutual-fund.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":11,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":12,"keywordType":"Outcome","textWithKeyword":"Then the debt MF investment type should be \"sip\"","stepMatchArguments":[{"group":{"start":38,"value":"\"sip\"","children":[{"start":39,"value":"sip","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"And the debt MF amount should be 5000","stepMatchArguments":[{"group":{"start":29,"value":"5000"},"parameterTypeName":"int"}]},{"pwStepLine":15,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"And the debt MF tenure should be 5 years","stepMatchArguments":[{"group":{"start":29,"value":"5"},"parameterTypeName":"int"}]},{"pwStepLine":16,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And the debt MF expected return should match the short-term fund default rate","stepMatchArguments":[]}]},
  {"pwTestLine":19,"pickleLine":18,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":20,"gherkinStepLine":19,"keywordType":"Action","textWithKeyword":"When I change the debt MF amount to 10000","stepMatchArguments":[{"group":{"start":31,"value":"10000"},"parameterTypeName":"int"}]},{"pwStepLine":21,"gherkinStepLine":20,"keywordType":"Outcome","textWithKeyword":"Then the debt MF corpus value should update without clicking calculate","stepMatchArguments":[]}]},
  {"pwTestLine":24,"pickleLine":23,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":25,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"Then I should see the debt MF money in hand amount","stepMatchArguments":[]},{"pwStepLine":26,"gherkinStepLine":25,"keywordType":"Outcome","textWithKeyword":"And the debt MF post-tax amount should be less than or equal to the corpus value","stepMatchArguments":[]}]},
  {"pwTestLine":29,"pickleLine":28,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":30,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then I should see the debt MF tax breakdown section","stepMatchArguments":[]},{"pwStepLine":31,"gherkinStepLine":30,"keywordType":"Outcome","textWithKeyword":"And the debt MF tax rule should mention indexation benefit","stepMatchArguments":[]}]},
  {"pwTestLine":34,"pickleLine":33,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":35,"gherkinStepLine":34,"keywordType":"Context","textWithKeyword":"Given inflation adjustment is on","stepMatchArguments":[]},{"pwStepLine":36,"gherkinStepLine":35,"keywordType":"Action","textWithKeyword":"When I view the debt MF results panel","stepMatchArguments":[]},{"pwStepLine":37,"gherkinStepLine":36,"keywordType":"Outcome","textWithKeyword":"Then I should see debt MF actual spending power adjusted for inflation","stepMatchArguments":[]}]},
  {"pwTestLine":40,"pickleLine":39,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":41,"gherkinStepLine":40,"keywordType":"Outcome","textWithKeyword":"Then I should see the debt MF evolution table","stepMatchArguments":[]},{"pwStepLine":42,"gherkinStepLine":41,"keywordType":"Outcome","textWithKeyword":"And the debt MF evolution table should have at least 1 year row","stepMatchArguments":[{"group":{"start":49,"value":"1"},"parameterTypeName":"int"}]}]},
  {"pwTestLine":45,"pickleLine":44,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then I should see the debt MF info panel","stepMatchArguments":[]},{"pwStepLine":47,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"And the debt MF info panel should show short-term debt return rate","stepMatchArguments":[]}]},
  {"pwTestLine":50,"pickleLine":49,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund","@edge"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"When I enter debt MF amount 499","stepMatchArguments":[{"group":{"start":23,"value":"499"},"parameterTypeName":"int"}]},{"pwStepLine":52,"gherkinStepLine":51,"keywordType":"Outcome","textWithKeyword":"Then I should see debt MF validation error \"Minimum investment amount is ₹500\"","stepMatchArguments":[{"group":{"start":38,"value":"\"Minimum investment amount is ₹500\"","children":[{"start":39,"value":"Minimum investment amount is ₹500","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":55,"pickleLine":54,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund","@edge"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":56,"gherkinStepLine":55,"keywordType":"Action","textWithKeyword":"When I enter debt MF tenure 51 years","stepMatchArguments":[{"group":{"start":23,"value":"51"},"parameterTypeName":"int"}]},{"pwStepLine":57,"gherkinStepLine":56,"keywordType":"Outcome","textWithKeyword":"Then I should see debt MF validation error \"Maximum tenure is 50 years\"","stepMatchArguments":[{"group":{"start":38,"value":"\"Maximum tenure is 50 years\"","children":[{"start":39,"value":"Maximum tenure is 50 years","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":60,"pickleLine":59,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund","@edge"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":61,"gherkinStepLine":60,"keywordType":"Action","textWithKeyword":"When I clear the debt MF amount","stepMatchArguments":[]},{"pwStepLine":62,"gherkinStepLine":61,"keywordType":"Outcome","textWithKeyword":"Then the debt MF calculator should show empty results state","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":62,"keywordType":"Outcome","textWithKeyword":"And the debt MF page should not crash","stepMatchArguments":[]}]},
  {"pwTestLine":66,"pickleLine":65,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund","@edge"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":67,"gherkinStepLine":66,"keywordType":"Action","textWithKeyword":"When I enter debt MF amount -1000","stepMatchArguments":[{"group":{"start":23,"value":"-1000"},"parameterTypeName":"int"}]},{"pwStepLine":68,"gherkinStepLine":67,"keywordType":"Outcome","textWithKeyword":"Then I should see a debt MF validation error or the value should be rejected","stepMatchArguments":[]}]},
  {"pwTestLine":71,"pickleLine":70,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund","@edge"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":72,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When I enter debt MF amount \"abc\"","stepMatchArguments":[{"group":{"start":23,"value":"\"abc\"","children":[{"start":24,"value":"abc","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":73,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then I should see a debt MF validation error for amount","stepMatchArguments":[]}]},
  {"pwTestLine":76,"pickleLine":75,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund","@edge"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":77,"gherkinStepLine":76,"keywordType":"Action","textWithKeyword":"When I enter debt MF amount 100000","stepMatchArguments":[{"group":{"start":23,"value":"100000"},"parameterTypeName":"int"}]},{"pwStepLine":78,"gherkinStepLine":77,"keywordType":"Action","textWithKeyword":"And I set debt MF tenure to 10 years","stepMatchArguments":[{"group":{"start":24,"value":"10"},"parameterTypeName":"int"}]},{"pwStepLine":79,"gherkinStepLine":78,"keywordType":"Outcome","textWithKeyword":"Then the debt MF corpus value should be approximately 17904241 within tolerance 5000","stepMatchArguments":[{"group":{"start":49,"value":"17904241"},"parameterTypeName":"int"},{"group":{"start":75,"value":"5000"},"parameterTypeName":"int"}]}]},
  {"pwTestLine":84,"pickleLine":88,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":85,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When I set debt MF inputs from golden \"DMF-14\"","stepMatchArguments":[{"group":{"start":33,"value":"\"DMF-14\"","children":[{"start":34,"value":"DMF-14","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":86,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then the debt MF corpus value should match golden \"DMF-14\" field corpusValue","stepMatchArguments":[{"group":{"start":45,"value":"\"DMF-14\"","children":[{"start":46,"value":"DMF-14","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":87,"gherkinStepLine":84,"keywordType":"Outcome","textWithKeyword":"And the debt MF post-tax amount should match golden \"DMF-14\" field postTaxAmount","stepMatchArguments":[{"group":{"start":48,"value":"\"DMF-14\"","children":[{"start":49,"value":"DMF-14","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":90,"pickleLine":89,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":91,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When I set debt MF inputs from golden \"DMF-20\"","stepMatchArguments":[{"group":{"start":33,"value":"\"DMF-20\"","children":[{"start":34,"value":"DMF-20","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":92,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then the debt MF corpus value should match golden \"DMF-20\" field corpusValue","stepMatchArguments":[{"group":{"start":45,"value":"\"DMF-20\"","children":[{"start":46,"value":"DMF-20","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":93,"gherkinStepLine":84,"keywordType":"Outcome","textWithKeyword":"And the debt MF post-tax amount should match golden \"DMF-20\" field postTaxAmount","stepMatchArguments":[{"group":{"start":48,"value":"\"DMF-20\"","children":[{"start":49,"value":"DMF-20","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":98,"pickleLine":92,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund","@edge"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":99,"gherkinStepLine":93,"keywordType":"Outcome","textWithKeyword":"Then I should see the debt MF investment breakdown chart or fallback","stepMatchArguments":[]}]},
  {"pwTestLine":102,"pickleLine":96,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":103,"gherkinStepLine":97,"keywordType":"Action","textWithKeyword":"When I set debt MF inputs from golden \"DMF-20\"","stepMatchArguments":[{"group":{"start":33,"value":"\"DMF-20\"","children":[{"start":34,"value":"DMF-20","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":104,"gherkinStepLine":98,"keywordType":"Outcome","textWithKeyword":"Then the debt MF tax rate label should be \"20% LTCG (Indexed)\"","stepMatchArguments":[{"group":{"start":37,"value":"\"20% LTCG (Indexed)\"","children":[{"start":38,"value":"20% LTCG (Indexed)","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":105,"gherkinStepLine":99,"keywordType":"Outcome","textWithKeyword":"And the debt MF tax amount should be approximately 5844 within tolerance 50","stepMatchArguments":[{"group":{"start":47,"value":"5844"},"parameterTypeName":"int"},{"group":{"start":69,"value":"50"},"parameterTypeName":"int"}]},{"pwStepLine":106,"gherkinStepLine":100,"keywordType":"Outcome","textWithKeyword":"And I should see debt MF indexation benefit details","stepMatchArguments":[]}]},
  {"pwTestLine":109,"pickleLine":103,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":110,"gherkinStepLine":104,"keywordType":"Action","textWithKeyword":"When I set debt MF inputs from golden \"DMF-21-STCG\"","stepMatchArguments":[{"group":{"start":33,"value":"\"DMF-21-STCG\"","children":[{"start":34,"value":"DMF-21-STCG","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":111,"gherkinStepLine":105,"keywordType":"Outcome","textWithKeyword":"Then the debt MF tax rate label should be \"30% slab\"","stepMatchArguments":[{"group":{"start":37,"value":"\"30% slab\"","children":[{"start":38,"value":"30% slab","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":112,"gherkinStepLine":106,"keywordType":"Outcome","textWithKeyword":"And the debt MF tax amount should be approximately 2952 within tolerance 50","stepMatchArguments":[{"group":{"start":47,"value":"2952"},"parameterTypeName":"int"},{"group":{"start":69,"value":"50"},"parameterTypeName":"int"}]}]},
  {"pwTestLine":115,"pickleLine":109,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":116,"gherkinStepLine":110,"keywordType":"Action","textWithKeyword":"When I set debt MF inputs from golden \"DMF-21-LTCG\"","stepMatchArguments":[{"group":{"start":33,"value":"\"DMF-21-LTCG\"","children":[{"start":34,"value":"DMF-21-LTCG","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":117,"gherkinStepLine":111,"keywordType":"Outcome","textWithKeyword":"Then the debt MF tax rate label should be \"20% LTCG (Indexed)\"","stepMatchArguments":[{"group":{"start":37,"value":"\"20% LTCG (Indexed)\"","children":[{"start":38,"value":"20% LTCG (Indexed)","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":118,"gherkinStepLine":112,"keywordType":"Outcome","textWithKeyword":"And the debt MF post-tax amount should match golden \"DMF-21-LTCG\" field postTaxAmount","stepMatchArguments":[{"group":{"start":48,"value":"\"DMF-21-LTCG\"","children":[{"start":49,"value":"DMF-21-LTCG","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":121,"pickleLine":115,"tags":["@smoke","@regression","@tax","@calculator-debt-mutual-fund"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given the default tax slab is 30 percent","isBg":true,"stepMatchArguments":[{"group":{"start":24,"value":"30"},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And inflation adjustment is off","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I am on the debt mutual fund calculator page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":122,"gherkinStepLine":116,"keywordType":"Action","textWithKeyword":"When I set debt MF inputs from golden \"DMF-22-SIP\"","stepMatchArguments":[{"group":{"start":33,"value":"\"DMF-22-SIP\"","children":[{"start":34,"value":"DMF-22-SIP","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":123,"gherkinStepLine":117,"keywordType":"Outcome","textWithKeyword":"Then the debt MF corpus value should match golden \"DMF-22-SIP\" field corpusValue","stepMatchArguments":[{"group":{"start":45,"value":"\"DMF-22-SIP\"","children":[{"start":46,"value":"DMF-22-SIP","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":124,"gherkinStepLine":118,"keywordType":"Action","textWithKeyword":"When I select debt MF investment type \"lumpsum\"","stepMatchArguments":[{"group":{"start":33,"value":"\"lumpsum\"","children":[{"start":34,"value":"lumpsum","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":125,"gherkinStepLine":119,"keywordType":"Action","textWithKeyword":"And I set debt MF inputs from golden \"DMF-22-LUMPSUM\"","stepMatchArguments":[{"group":{"start":33,"value":"\"DMF-22-LUMPSUM\"","children":[{"start":34,"value":"DMF-22-LUMPSUM","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":126,"gherkinStepLine":120,"keywordType":"Outcome","textWithKeyword":"Then the debt MF corpus value should match golden \"DMF-22-LUMPSUM\" field corpusValue","stepMatchArguments":[{"group":{"start":45,"value":"\"DMF-22-LUMPSUM\"","children":[{"start":46,"value":"DMF-22-LUMPSUM","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end